apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/metallb/frr-k8s/config/default/?timeout=120&ref=main
- ../native
patchesStrategicMerge:
- speaker-patch.yaml
images:
- name: quay.io/metallb/frr-k8s
  newTag: main
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      kind: Role
      name: metallb-system:pod-lister
      namespace: metallb-system
    path: role-patch.yaml
