resources:
- manifests.yaml
- service.yaml
- secret.yaml

configurations:
- kustomizeconfig.yaml

namePrefix: metallb-

patchesJson6902:
- path: patches/patch_webhook_configuration.yaml
  target:
    version: v1
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration

