
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - service
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - service/status
  verbs:
  - update
- apiGroups:
  - corev1
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - corev1
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - corev1
  resources:
  - node
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - corev1
  resources:
  - service
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metallb.io
  resources:
  - addresspools
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - metallb.io
  resources:
  - bfdprofiles
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - metallb.io
  resources:
  - bgppeers
  verbs:
  - get
  - list
  - watch
