apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../frr
  - ../webhook
  - rbac.yaml

patchesStrategicMerge:
  - controller-webhook-patch.yaml
  - webhookcainjection-patch.yaml
  - crd-conversion-patch.yaml
  - crdcainjection-patch.yaml
  - webhookservicecainjection_patch.yaml
  - permission-patch.yaml

namespace: metallb-system
