name: Add Labels

on:
  pull_request:
    types: [opened, edited]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: fetch kind
        id: kind
        run: |
          kind=$(${{ github.event.comment.body }} | awk '/kind/{print $2}')
          echo "kind=$kind" >> $GITHUB_OUTPUT
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.kind.outputs.kind != "" }}
        with:
          labels: |
            ${{ steps.kind.outputs.kind }}
