name: Site Build 

on:
  pull_request:
    paths:
      - 'website/**'
      - 'netlify.toml'
      - 'api/**'
    branches:
      - "main"
      - "v**"
  workflow_dispatch:

jobs:
  validate-website-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: wagoid/commitlint-github-action@v4
      
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo pip3 install invoke semver pyyaml

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'

      - name: Build
        run: cd ./website && hugo

      - name: Check api docs
        run: |
          inv generateapidocs
          inv checkchanges --action="run inv generateapidocs"
